### ISSUE TITLE
Fixes for v0.4.0

### ISSUE THREAD

**Issue by kasunben** [thinkholic/wordpress-cli#40]
**TODO**

- [x] Add proper logs, messages and notifications
- [x] Add `index.php` file to empty theme canvas (unless it's not working) [bug]
- [x] Do necessary changes on DB when update database config.
- [x] Improve the Server logs.
- [x] Change a bit `site.json`
```
{
  "siteName": "testwp",
  "siteVersion": "1.0.0",
  "cliVersion": "0.4.0",
  "db": {
    "mysqlDbHost": "127.0.0.1",
    "mysqlDbPort": "3306",
    "mysqlDbUser": "root",
    "mysqlDbPwd": "root",
    "mysqlDbName": "testwp1234",
    "mysqlDbTblPrefix": "wp_"
  }
}
```
- [x] Remove `replaceAll` method [1](https://github.com/thinkholic/wordpress-cli/blob/master/lib/actions/template.js#L8)
- [x] Refactor the codebase
